name: Build Multi-Brand Websites

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    env:
      QUARTO_CHROME_HEADLESS_MODE: "new"

    steps:
    - uses: actions/checkout@v4

    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        version: pre-release

    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: release

    - name: Setup R packages
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        packages: any::rmarkdown, any::yaml

    - name: Install yq
      run: |
        sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
        sudo chmod a+x /usr/local/bin/yq

    - name: Create Directory Structure
      run: |
        mkdir -p _site

    - name: Generate Brand Websites
      run: |
        # Get list of all brand directories
        brand_dirs=$(find . -type f -name "_brand.yml" -exec dirname {} \; | sed 's|^./||')

        # Function to modify _quarto.yml for each brand
        process_brand() {
          local brand_dir=$1
          local brand_name=$(basename "$brand_dir")
          echo "Processing ${brand_name}..."
          
          # Create temporary directory for this brand
          temp_dir="temp_${brand_name}"
          mkdir -p "$temp_dir"
          
          # Copy necessary files to temp directory
          cp _quarto.yml "${temp_dir}/"
          cp demo-index.qmd "${temp_dir}/index.qmd"
          
          # Copy entire brand directory to temp directory
          cp -r "${brand_dir}" "${temp_dir}/"
          
          # Update brand path to use local copy
          yq -i '.brand = "'"${brand_name}/_brand.yml"'"' "${temp_dir}/_quarto.yml"
          
          # Render in temp directory
          cd "$temp_dir"
          quarto render
          cd ..
          
          # Move rendered output to final location
          mkdir -p "_site/${brand_name}"
          mv "${temp_dir}/_site/*" "_site/${brand_name}/"
        }

        # Process each brand directory
        for brand_dir in $brand_dirs; do
          process_brand "$brand_dir"
        done

    - name: Generate Gallery Index
      run: |
        # Render the main index page using gallery-specific _quarto.yml
        quarto render index.qmd --config gallery_quarto.yml
    
    - name: Upload Pages Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: "_site"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
    
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
