name: Build Multi-Brand Websites

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    env:
      QUARTO_CHROME_HEADLESS_MODE: "new"

    steps:
    - uses: actions/checkout@v4

    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        version: pre-release

    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: release

    - name: Setup R packages
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        packages: any::rmarkdown, any::yaml

    - name: Install yq
      run: |
        sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq &&\
        sudo chmod +x /usr/bin/yq

    - name: Create Directory Structure
      run: |
        mkdir -p _site

    - name: Generate Brand Websites
      run: |
          # Process each brand
          for brand_dir in $(find . -type f -name "_brand.yml" -exec dirname {} \; | sed 's|^./||'); do
            echo "Processing $brand_dir..."
            if ! .github/scripts/process-brand.sh "$brand_dir"; then
                echo "Failed to process $brand_dir"
                exit 1
            fi
          done
    - name: Generate Gallery Index
      run: |
        # Render the main index page using gallery-specific _quarto.yml
        quarto render index.qmd --config gallery_quarto.yml
    
    - name: Upload Pages Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: "_site"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
    
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
